#+TITLE: Computer Vision Notes
#+AUTHOR: Vi Kumar

Loads of information over here - https://www.mathworks.com/products/computer-vision.html

So our drone is a line-following robot (LFR) that needs to identify waypoint, calculate a trajectory, and traverse through the path as quickly as possible.

We have an IMU (Inertial Measurement Unit) as well as a Monocular Camera.
- The IMU returns an accurate estimate of state for small time intervals, but suffers from large drift due to integrating the inertial sensor measurements.
- The visual odometry is good for long-term estimation but is inaccurate for short time intervals.

By creating a tightly-coupled control framework, we can utilize the complimentary characteristics of our sensors to create a UAS that is capable of localization, perception, control, and path planning. VI odometry, the topic described earlier, has been an active research topic thanks to cheap sensors and better embedded microcontrollers - we'll be utilizing a bunch of previous research to make our model. In the process, we'll be making documentation that explains everything for a noob - it's a very broad topic that takes way too much time to figure out.
